# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-gpts-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://alertsimage.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2c8004da58a54266b9ef4fb6a6e37231 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b60d081c8cbc4cdcbd898260c9f94ff5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: alertsimage.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2c8004da58a54266b9ef4fb6a6e37231 }}/gpts-teacher-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-gpts-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a53eda27adf84d088d93cdcf8bd1d3f4 }}
        images: 'alertsimage.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2c8004da58a54266b9ef4fb6a6e37231 }}/gpts-teacher-app:${{ github.sha }}'